name: deploy_cake_website

on: [workflow_dispatch] 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        -uses: actions/checkoutv@2
         with:
          path: repo
        - uses: azure/login@v1
          with:
            client-id: ${{AZURE_CLIENT_ID}}
            tenant-id: ${{AZURE_TENANT_ID}}
            subscription-id: ${{AZURE_SUBSCROPTION_ID}}